### PR TITLE
Improve Regex usage

### PR DESCRIPTION
**Pull request by Tim-Maes**
Feedback applied from user @daisplusplus

See issue #21 

I also tried using the official T4 pattern but it did not filter out Class Feature and Control blocks - it did work for the output/boilerplate but very inconsistent.

### CODE REVIEW

**Comment by daiplusplus** [comment]
> @Tim-Maes but it did not filter out Class Feature and Control blocks - it did work for the output/boilerplate but very inconsistent.

Can you post an example?

**Comment by Tim-Maes** [comment]
This RegEx :
```
private const string VSOfficialPatternCleaner = /* language=regex */ @"(?<boilerplate>^(\\)+)(?=<\#)|
                                                                       (?<=([^\\]|^)(\\)*)<\#@(?<directive>.*?)(?<=[^\\](\\)*)\#>|
                                                                       (?<=([^\\]|^)(\\)*)<\#\+(?<classfeature>.*?)(?<=[^\\](\\)*)\#>|
                                                                       (?<=([^\\]|^)(\\)*)<\#=(?<expression>.*?)(?<=[^\\](\\)*)\#>|
                                                                       (?<=([^\\]|^)(\\)*)<\#(?<statement>.*?)(?<=[^\\](\\)*)\#>|
                                                                       (?<boilerplate>.+?)(?=((?<=[^\\](\\)*)<\#))|
                                                                       (?<boilerplate>.+)(?=$)";
```

And implemented like this:

```

            MatchCollection matches = Constants.Regexen.VSOfficialPattern.Matches(document);

            foreach (Match match in matches)
            {
                if (match.Groups["directive"].Success)
                {
                    type = _classificationTypeRegistry.GetClassificationType(Constants.DirectiveBlock);
                    spans.Add(CreateClassificationSpan(snapshot, match.Groups["directive"].Index, match.Groups["directive"].Length, type));
                }

                if (match.Groups["classfeature"].Success)
                {
                    type = _classificationTypeRegistry.GetClassificationType(Constants.ClassFeatureBlock);
                    spans.Add(CreateClassificationSpan(snapshot, match.Groups["classfeature"].Index, match.Groups["classfeature"].Length, type));
                }
// .....
```

Results in this (installing the locally generated package):

image


Debugging 0 matches:
image

**Comment by daiplusplus** [comment]
Is [the code in your post above](https://github.com/Tim-Maes/T4Editor/pull/24#issuecomment-1764635335) included in this repo for me to `git clone` and reproduce? If so, which commit-id / hash and file path is it in?

**Comment by Tim-Maes** [comment]
There is a feature branch [here](https://github.com/Tim-Maes/T4Editor/tree/feature/official-regex), latest commit.

But honestly, the long term solution here would be to get rid of the RegEx and write some kind of parser. Some day

**Comment by daiplusplus** [comment]
Thanks - I'll be able to take a look tomorrow.

**Pull request merged**
